version: 2
updates:
  - package-ecosystem: "npm"
    assignees:
      - "cooperwalbrun"
    commit-message:
      prefix: "npm"
      include: "scope"
    directory: "/"
    open-pull-requests-limit: 1
    reviewers:
      - "cooperwalbrun"
    rebase-strategy: "auto"
    schedule:
      interval: "daily"
      time: "11:00"
      timezone: "America/Chicago"
    target-branch: "master"
