version: 2
updates:
  - package-ecosystem: "npm"
    assignees:
      - "cooperwalbrun"
    commit-message:
      prefix: "npm"
      include: "scope"
    directory: "/"
    open-pull-requests-limit: 1
    rebase-strategy: "auto"
    schedule:
      interval: "daily"
      time: "11:00"
      timezone: "America/Chicago"
    target-branch: "master"
    groups:
      css:
        patterns:
          - "autoprefixer"
          - "postcss"
          - "sass"
      development-tools:
        patterns:
          - "husky"
          - "lint-staged"
      npm-scripts:
        patterns:
          - "cross-env"
          - "del-cli"
          - "npm-run-all"
      prettier:
        patterns:
          - "prettier"
      stylelint:
        patterns:
          - "stylelint"
          - "stylelint-config-html"
          - "stylelint-config-prettier-scss"
          - "stylelint-config-sass-guidelines"
          - "stylelint-config-standard-scss"
      typescript:
        patterns:
          - "@types/node"
          - "tslib"
          - "typescript"
      unit-testing:
        patterns:
          - "@testing-library/*"
          - "jsdom"
      vite:
        patterns:
          - "@vitest/coverage-v8"
          - "vite"
          - "vitest"
          - "typescript"
      web-ext:
        patterns:
          - "web-ext"
