codecov:
  require_ci_to_pass: true

coverage:
  precision: 2
  round: down
  range: "90...100"
  status:
    patch:
      default:
        target: 30%
    project:
      default:
        target: 95%

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: false

ignore:
  - "src/content-script.ts"
  - "src/popup/main.ts"
  - "src/**/*.d.ts"
