#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# See: https://github.com/okonet/lint-staged/issues/1164#issuecomment-1177561594 and
# https://github.com/typicode/husky/issues/968#issuecomment-1176848345
exec >/dev/tty 2>&1

lint-staged
