name: master
on:
  push:
    branches:
      - master
jobs:
  unit-test:
    name: Unit Test with Code Coverage Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: Set up Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm install
      - name: Unit test with code coverage analysis
        run: npm run test:coverage
      - name: Upload test coverage report to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          flags: node20
          files: coverage/cobertura-coverage.xml
