name: master
on:
  push:
    branches:
      - master
jobs:
  unit-test:
    name: Unit Test with Code Coverage Analysis
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        node-version: [16, 18]
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: Set up Node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm install
      - name: Unit test with code coverage analysis on Node ${{ matrix.node-version }}
        run: npm run test:coverage
      - name: Upload test coverage report to Codecov
        uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: true
          flags: node${{ matrix.node-version }}
          files: coverage/cobertura-coverage.xml
